---
title: "The Drivers of Commuter Behavior in France"
author: "Mathilde VALLAT, Yesmine HACHANA"
format: html
---

## Loading the two final datasets

### Loading stops_france
```{r}
library(vroom)
library(here)
here::i_am("Final_Project_Commuter_behavior.Rproj")

source <- "https://www.data.gouv.fr/fr/datasets/r/69cf54c6-6591-4920-b1d6-2a5292964606"
local_name <- "stops_france.csv.gz"
local_dir <- "data"
## is the directory available?
if (!dir.exists(here(local_dir))) {
  ## create the directory if needed
  dir.create(here(local_dir))
}
## is the file available?
if (!file.exists(here(local_dir, local_name))) {
  ## we need to download it
  stops_france <- vroom(source)
  ## let's save the file to avoid useless downloading
  vroom_write(stops_france, here(local_dir, local_name), delim = ",")
} else {
  ## we need only to load it
  stops_france <- vroom(here(local_dir, local_name))
}
```
### Loading mob_pro

```{r}
library(zip)
# Define variables
source <- "https://www.insee.fr/fr/statistiques/fichier/8205896/RP2021_mobpro.zip"
local_name <- "RP2021_mobpro.zip"
local_dir <- "data"
csv1_name <- "FD_MOBPRO_2021.csv"
csv2_name <- "varmod_mobpro_2021.csv"
# Check if the directory exists, create if not
if (!dir.exists(here(local_dir))) {
  dir.create(here(local_dir))
}
# Check if the ZIP file exists locally
if (!file.exists(here(local_dir, local_name))) {
  # Download the ZIP file
  download.file(source, destfile = here(local_dir, local_name), mode = "wb")
}
# Unzip the file
unzip(here(local_dir, local_name), exdir = here(local_dir))
# Load the first CSV file
mob_pro <- vroom(here(local_dir, csv1_name))
# Load the second CSV file
var_mob_pro <- vroom(here(local_dir, csv2_name))
```


